services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: emotli_chat
      MYSQL_USER: emotli
      MYSQL_PASSWORD: emotli_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=mysql
      - DB_USER=emotli
      - DB_PASSWORD=emotli_password
      - DB_NAME=emotli_chat
      - JWT_SECRET=your_jwt_secret
      - EMAIL_USER=your_gmail@gmail.com
      - EMAIL_PASS=your_app_password
      - CLIENT_URL=http://localhost
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql-data:
